### PR TITLE
Added homework calculator

### PR DESCRIPTION
**Pull request by wrensf**
Hello, 

Here is the Class 2 in-lab calculator.

Thanks,

Rena

### CODE REVIEW

**Comment by Borgaard** [comment]
Hi @wrensf,

Can you reopen this pull request? I can't merge it into the `bewd11-homework` repo if it's closed.

**Comment by wrensf** [comment]
Oh, sorry. I will do that when I get home.

**Comment by wrensf** [comment]
Hello, 

Please let me know if this reopened it. 
Thanks!

**Comment by Borgaard** [comment]
@wrensf Yeah, looks great! Thanks! :+1:

**Comment by Borgaard** [comment]
@wrensf Can you create a `hw_1` inside of `RenaThiagarajan_wrensf` directory and move `calculator.rb` in there?

This is how your directory structure currently looks:
`RenaThiagarajan_wrensf/calculator.rb`

It should look like this:
`RenaThiagarajan_wrensf/hw_1/calculator.rb`

To fix this, navigate to `RenaThiagarajan_wrensf` and `mkdir hw_1`. You can now move your homework with the move command: `mv calculator.rb hw_1`.

Once you've done that, `git add -A` > `git commit -m "moved calculator to hw_1 directory"` > `git push origin master`.
No need to create a new pull request; this one will automatically update with your changes.

**Comment by wrensf** [comment]
@Borgaard Nicole, Could you let me know if I got it right this time? I added hw_1 and moved calculator into that folder. Thanks,

**Comment by Borgaard** [comment]
@wrensf just need you to add, commit and push it. We can do this before class as well.

**Comment by Borgaard** [comment]
Thanks, @wrensf!

**Pull request merged**
